CREATE TABLE "salesInvoicesRaw" (
	"id" integer PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "salesInvoicesRaw_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"invoiceDate" date NOT NULL,
	"gstTaxInvoiceDate" date NOT NULL,
	"recipient" integer NOT NULL,
	"recipientName" varchar NOT NULL,
	"plant" integer NOT NULL,
	"materialDescription" varchar NOT NULL,
	"qty" numeric NOT NULL,
	"freightByCustRate" numeric,
	"freightByKciRate" numeric,
	"freightByKciValue" numeric,
	"transporterName" varchar,
	"lrNo" varchar,
	"lrDat" date,
	"vehicleNo" varchar,
	"recipientCity" varchar NOT NULL,
	"placeOfSupply" varchar,
	"salesOrg" integer NOT NULL,
	"salesOrgDescription" varchar NOT NULL,
	"divDescription" varchar NOT NULL,
	"contractNo" integer,
	"internalRefNo" integer NOT NULL,
	"invItem" integer,
	"invoiceType" varchar,
	"invoiceTypeDescription" varchar,
	"incoterms" varchar,
	"incotermsDescription" varchar,
	"soDate" date NOT NULL,
	"soQty" numeric NOT NULL,
	"giNo" integer,
	"giDate" date,
	"gstTaxInvNo" varchar,
	"recipientGstRegNo" varchar,
	"materialCode" integer NOT NULL,
	"hsnCode" integer,
	"invoiceCurrency" varchar,
	"basicRate" numeric NOT NULL,
	"basicAmount" numeric NOT NULL,
	"receiptVoucherNo" varchar,
	"receiptVoucherDate" date,
	"freightByCust" integer,
	"taxableValue" numeric,
	"commissionRate" numeric,
	"commissionAmount" numeric,
	"assessableValue" numeric,
	"sgstPct" numeric,
	"sgstAmount" numeric,
	"cgstPct" numeric,
	"cgstAmount" numeric,
	"igstPct" numeric,
	"igstAmount" numeric,
	"ugstPct" numeric,
	"ugstAmount" numeric,
	"tcsAmount" numeric,
	"tcsSaleAmount" numeric,
	"invoiceValue" numeric,
	"netRealisation" numeric,
	"ewayBillNo" varchar,
	"materialGroup" varchar,
	"materialDescription2" varchar NOT NULL,
	"uom" varchar NOT NULL,
	CONSTRAINT "salesInvoicesRaw_internalRefNo_unique" UNIQUE("internalRefNo")
);
