CREATE TABLE "salesInvoicesRaw" (
	"id" integer PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "salesInvoicesRaw_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"assessableValue" numeric,
	"basicAmount" numeric,
	"basicRate" numeric,
	"cgstAmount" numeric,
	"cgstPct" numeric,
	"commissionRate" numeric,
	"commissionValue" numeric,
	"consignee" integer NOT NULL,
	"consigneeCity" varchar NOT NULL,
	"consigneeGstRegNo" varchar NOT NULL,
	"consigneeName" varchar NOT NULL,
	"consigneePlaceOfSupplyCode" integer NOT NULL,
	"consigneeRegion" varchar NOT NULL,
	"contractNo" bigint,
	"contractDate" date,
	"distChannel" integer NOT NULL,
	"distChannelDescription" varchar NOT NULL,
	"division" integer NOT NULL,
	"divDescription" varchar NOT NULL,
	"exchangeRate" numeric,
	"ewayBillNo" varchar,
	"freightByCustRate" numeric,
	"freightByCustValue" numeric,
	"freightByKciRate" numeric,
	"freightByKciValue" numeric,
	"giDate" date,
	"giNo" bigint,
	"gstTaxInvDate" date NOT NULL,
	"gstTaxInvNo" varchar NOT NULL,
	"hsnCode" integer,
	"igstAmount" numeric,
	"igstPct" numeric,
	"incoterms" varchar,
	"incotermsDescription" varchar,
	"internalRefNo" bigint NOT NULL,
	"invItem" integer,
	"invDate" date NOT NULL,
	"invoiceCurrency" varchar,
	"invoiceType" varchar,
	"invoiceTypeDescription" varchar,
	"invoiceValue" numeric,
	"lrDate" date,
	"lrNo" varchar,
	"materialCode" integer NOT NULL,
	"materialDescription" varchar NOT NULL,
	"netRealisation" numeric,
	"netRealisationPerUnit" numeric,
	"placeOfSupply" varchar NOT NULL,
	"placeOfSupplyCode" integer NOT NULL,
	"plant" integer NOT NULL,
	"poNumber" varchar,
	"qty" numeric NOT NULL,
	"receiptVoucherDate" date,
	"receiptVoucherNo" varchar,
	"recipient" integer NOT NULL,
	"recipientCity" varchar NOT NULL,
	"recipientGstRegNo" varchar NOT NULL,
	"recipientName" varchar NOT NULL,
	"salesOrgDescription" varchar NOT NULL,
	"sgstAmount" numeric,
	"sgstPct" numeric,
	"soDate" date NOT NULL,
	"soQty" numeric NOT NULL,
	"taxableValue" numeric,
	"tcsAmount" numeric,
	"tcsSaleAmount" numeric,
	"transporterName" varchar,
	"ugstAmount" numeric,
	"ugstPct" numeric,
	"uom" varchar NOT NULL,
	"vehicleNo" varchar,
	CONSTRAINT "salesInvoicesRaw_internalRefNo_unique" UNIQUE("internalRefNo")
);
